package com.polentita.music.domain.model

import com.polentita.music.core.database.SongEntity

data class Song(
    val id: Long,
    val title: String,
    val artist: String,
    val albumId: Long?,
    val albumName: String,
    val genre: String,
    val year: Int?,
    val trackNumber: Int?,
    val discNumber: Int?,
    val durationMs: Long,
    val contentUri: String,
    val originalFileName: String,
    val displayFileName: String,
    val mimeType: String,
    val fileSize: Long,
    val coverUri: String?,
    val sourceType: String,
    val sourceUrl: String?,
    val dateAdded: Long,
    val dateModified: Long,
    val lastPlayedAt: Long?,
    val playCount: Long,
    val isFavorite: Boolean,
    val isAvailable: Boolean,
    val checksum: String,
    val isrc: String? = null,
)

fun SongEntity.toModel() = Song(
    id = id,
    title = title,
    artist = artist,
    albumId = albumId,
    albumName = albumName,
    genre = genre,
    year = year,
    trackNumber = trackNumber,
    discNumber = discNumber,
    durationMs = durationMs,
    contentUri = contentUri,
    originalFileName = originalFileName,
    displayFileName = displayFileName,
    mimeType = mimeType,
    fileSize = fileSize,
    coverUri = coverUri,
    sourceType = sourceType,
    sourceUrl = sourceUrl,
    dateAdded = dateAdded,
    dateModified = dateModified,
    lastPlayedAt = lastPlayedAt,
    playCount = playCount,
    isFavorite = isFavorite,
    isAvailable = isAvailable,
    checksum = checksum,
    isrc = isrc,
)

fun Song.toEntity() = SongEntity(
    id = id,
    title = title,
    artist = artist,
    albumId = albumId,
    albumName = albumName,
    genre = genre,
    year = year,
    trackNumber = trackNumber,
    discNumber = discNumber,
    durationMs = durationMs,
    contentUri = contentUri,
    originalFileName = originalFileName,
    displayFileName = displayFileName,
    mimeType = mimeType,
    fileSize = fileSize,
    coverUri = coverUri,
    sourceType = sourceType,
    sourceUrl = sourceUrl,
    dateAdded = dateAdded,
    dateModified = dateModified,
    lastPlayedAt = lastPlayedAt,
    playCount = playCount,
    isFavorite = isFavorite,
    isAvailable = isAvailable,
    checksum = checksum,
    isrc = isrc,
)

enum class SongSort { TITLE, ARTIST, ALBUM, DATE_ADDED, DATE_MODIFIED, DURATION, PLAY_COUNT, LAST_PLAYED }

data class SongFilter(
    val favoriteOnly: Boolean = false,
    val sourceType: String? = null,
    val coverMode: Int = 0,
    val availableMode: Int = 0,
    val artist: String? = null,
    val album: String? = null,
    val genre: String? = null,
    val year: Int? = null,
)
